using UnitsDrafts;
using Units_222_Draft.items;
using Units_222_Draft.units;
using Units_222_Draft.Stats;
using System.Diagnostics;
 Console.WriteLine("пососал");
var th = new Townhall();
var br = new Barracs();
var bh = th.SpawnBishop();
var ft = br.SpawnFootman();
var arch = br.SpawnArcher();
var ps = th.SpawnPeasant();
Fight.Duel(ft, arch);